AVRO-2255: Shellcheck During Lint

diff --git a/lang/c/tests/test_valgrind b/lang/c/tests/test_valgrind
--- a/lang/c/tests/test_valgrind
+++ b/lang/c/tests/test_valgrind
@@ -13,21 +13,15 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
 # implied.  See the License for the specific language governing
 # permissions and limitations under the License. 
+
 set +e
 set -x
 
-if ! which valgrind; then
-	echo "Unable to find valgrind installed. Test will not run."
-	# This special exit value will show that we skipped this test
-	exit 77
+if ! command -v valgrind; then
+  echo "Unable to find valgrind installed. Test will not run."
+  # This special exit value will show that we skipped this test
+  exit 77
 fi
 
-../libtool execute valgrind --leak-check=full -q test_avro_data 2>&1 |\
-grep -E '^==[0-9]+== '
-if [ $? -eq 0 ]; then
-	# Expression found. Test failed.
-	exit 1
-else
-	# We're all clean
-	exit 0
-fi
+../libtool execute valgrind --leak-check=full -q test_avro_data 2>&1 |
+  { ! grep -E '^==[0-9]+== '; }
